appname: "EABShortener"
charset: "UTF-8"
template: "template_toolkit"
plugins:
  Database:
    driver: 'SQLite'
    database: 'data.sqlite'
engines:
  template_toolkit:
    encoding:  'utf8'
    start_tag: '[%'
    end_tag:   '%]'
max_links: 50
