# configuration file for production environment
log: "warning"
logger: "file"
warnings: 0
show_errors: 0
route_cache: 1
plugins:
  Database:
    driver: 'SQLite'
    database: '/var/db/dancer/eab-shorten.sqlite'

